SELECT "ORDER_ID",
    "CUSTOMER_ID",
    "ORDER_APPROVED_AT",
    "ORDER_DELIVERED_CARRIER_DATE",
    "ORDER_DELIVERED_CUSTOMER_DATE",
    "ORDER_PURCHASE_TIMESTAMP",
    "ORDER_ESTIMATED_DELIVERY_DATE",
    "ORDER_STATUS",
    CASE
        WHEN DATEDIFF(SECOND, "ORDER_PURCHASE_TIMESTAMP", "ORDER_APPROVED_AT") <= 86400 THEN '0-24 hours'
        ELSE CASE
        WHEN DATEDIFF(SECOND, "ORDER_PURCHASE_TIMESTAMP", "ORDER_APPROVED_AT") <= 172800 THEN '24-48 hours'
        ELSE CASE
        WHEN DATEDIFF(SECOND, "ORDER_PURCHASE_TIMESTAMP", "ORDER_APPROVED_AT") <= 259200 THEN '48-72 hours'
        ELSE CASE
        WHEN DATEDIFF(SECOND, "ORDER_PURCHASE_TIMESTAMP", "ORDER_APPROVED_AT") <= 345600 THEN '72-96 hours'
        ELSE 'Over 96 hours'
        END
        END
        END
    END AS "TIME_TO_APPROVAL_BINS",
    COALESCE(COALESCE(DATEDIFF(SECOND, "ORDER_PURCHASE_TIMESTAMP", "ORDER_APPROVED_AT"), 0) / 60, 0) / 60 AS "TIME_TO_APPROVAL_IN_HOURS",
    DATEDIFF(SECOND, "ORDER_PURCHASE_TIMESTAMP", "ORDER_APPROVED_AT") AS "TIME_TO_APPROVAL_IN_SECONDS",
    CASE
        WHEN CAST("ORDER_DELIVERED_CUSTOMER_DATE" AS VARCHAR) IS NULL OR CAST("ORDER_DELIVERED_CUSTOMER_DATE" AS VARCHAR) = '' THEN ''
        ELSE CASE
        WHEN "ORDER_DELIVERED_CUSTOMER_DATE" < "ORDER_ESTIMATED_DELIVERY_DATE" THEN 'early'
        ELSE CASE
        WHEN "ORDER_DELIVERED_CUSTOMER_DATE" = "ORDER_ESTIMATED_DELIVERY_DATE" THEN 'on-time'
        ELSE 'late'
        END
        END
    END AS "DELIVERY_STATUS"
FROM {{ref('stg_olist_orders')}} AS "dbt_jeck_bronze__stg_olist_orders"
GROUP BY 2, 12, 3, 4, 5, 7, 1, 6, 8, 9, 10, 11
