SELECT "PRODUCT_ID",
    "PRODUCT_CATEGORY_NAME_ENGLISH",
    "PRODUCT_NAME_LENGTH",
    "PRODUCT_DESCRIPTION_LENGTH",
    "PRODUCT_PHOTOS_QTY",
    CASE
        WHEN "PRODUCT_PHOTOS_QTY" > 1 THEN TRUE
        ELSE FALSE
    END AS "HAS_MULTIPLE_PHOTOS",
    "PRODUCT_WEIGHT_G",
    "PRODUCT_LENGTH_CM",
    "PRODUCT_HEIGHT_CM",
    "PRODUCT_WIDTH_CM"
FROM "DBT_JECK_BRONZE"."STG_OLIST_PRODUCTS" AS "dbt_jeck_bronze__stg_olist_products"
GROUP BY 6, 2, 4, 9, 1, 8, 3, 5, 7, 10
