SELECT "SELLER_ID",
    "SELLER_ZIP_CODE_PREFIX",
    CASE
        WHEN LENGTH(CAST("SELLER_ZIP_CODE_PREFIX" AS VARCHAR)) = 4 THEN CONCAT('0', COALESCE(CAST("SELLER_ZIP_CODE_PREFIX" AS VARCHAR), ''))
        ELSE CAST("SELLER_ZIP_CODE_PREFIX" AS VARCHAR)
    END AS "SELLER_ZIP_CODE_FIXED",
    "SELLER_CITY",
    "SELLER_STATE",
    CONCAT(COALESCE(CONCAT(COALESCE("SELLER_CITY", ''), ', '), ''), COALESCE("SELLER_STATE", '')) AS "SELLER_CITY_STATE"
FROM "DBT_JECK_BRONZE"."STG_OLIST_SELLERS" AS "dbt_jeck_bronze__stg_olist_sellers"
GROUP BY 4, 6, 1, 5, 3, 2
