SELECT "CUSTOMER_ID",
    "CUSTOMER_UNIQUE_ID",
    CONCAT("CUSTOMER_CITY", ', ', "CUSTOMER_STATE") AS "CUSTOMER_CITY_STATE",
    CASE
        WHEN LENGTH(CAST("CUSTOMER_ZIP_CODE_PREFIX" AS VARCHAR)) = 4 THEN CONCAT('0', COALESCE(CAST("CUSTOMER_ZIP_CODE_PREFIX" AS VARCHAR), ''))
        ELSE CAST("CUSTOMER_ZIP_CODE_PREFIX" AS VARCHAR)
    END AS "CUSTOMER_ZIP_CODE_FIXED", 
  "CUSTOMER_CITY" AS "CUSTOMER_CITY",
  "CUSTOMER_STATE" AS "CUSTOMER_STATE"
FROM "DBT_JECK_BRONZE"."STG_OLIST_CUSTOMERS" AS "dbt_jeck_bronze__stg_olist_customers"
GROUP BY 3, 1, 2, 4, 5, 6
