# models/bronze/sources.yml
version: 2 

sources: 
  - name: olist_raw_data 
    database: OLIST 
    schema: RAW 
    tables: 
      - name: customers 
      - name: geolocation
      - name: orders 
      - name: order_items
      - name: order_payments
      - name: order_reviews 
      - name: products
      - name: product_category_name_translation
      - name: sellers 